# Generated by Django 3.2.8 on 2025-08-14 17:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('rol', models.CharField(default='noc', max_length=20)),
            ],
            options={
                'db_table': 'Usuarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='visita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoidentificacion', models.CharField(max_length=20)),
                ('identificacion', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo', models.CharField(blank=True, max_length=50, null=True)),
                ('ingresavehiculo', models.BooleanField(default=False)),
                ('placa', models.CharField(blank=True, max_length=10, null=True)),
                ('notarjeta', models.CharField(max_length=20)),
                ('autoriza', models.CharField(max_length=100)),
                ('foto', models.TextField(blank=True, null=True)),
                ('firma', models.TextField(blank=True, null=True)),
                ('usuario_noc', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('horadeingresonoc', models.DateTimeField(blank=True, null=True)),
                ('horadesalidanoc', models.DateTimeField(blank=True, null=True)),
                ('motivovisita', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'visita',
                'managed': True,
            },
        ),
    ]
