# Generated by Django 3.2.8 on 2025-08-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlacceso', '0002_auto_20250815_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='nombre_archivo_firma',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='nombre_archivo_foto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
